-- SQL Script for Initializing the Database

-- Disable foreign key checks temporarily to avoid issues with table creation order
SET FOREIGN_KEY_CHECKS=0;

--
-- Table structure for table `sectors`
--
DROP TABLE IF EXISTS `sectors`;
CREATE TABLE `sectors` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `sectors`
--
LOCK TABLES `sectors` WRITE;
INSERT INTO `sectors` (`name`) VALUES
('Gerência'),
('NTI'),
('Administrativo'),
('Comunicação'),
('Programação'),
('Alimentação'),
('Odontologia'),
('Infraestrutura'),
('Serviços');
UNLOCK TABLES;

--
-- Table structure for table `persons`
--
DROP TABLE IF EXISTS `persons`;
CREATE TABLE `persons` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sector_id` INT NOT NULL,
  FOREIGN KEY (`sector_id`) REFERENCES `sectors`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Table structure for table `extensions`
--
DROP TABLE IF EXISTS `extensions`;
CREATE TABLE `extensions` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `number` VARCHAR(50) NOT NULL UNIQUE,
  `type` ENUM('Interno', 'Externo') NOT NULL,
  `sector_id` INT,
  `person_id` INT NULL, -- Nullable, as an extension might not be assigned to a person initially
  `status` ENUM('Vago', 'Atribuído') NOT NULL DEFAULT 'Vago',
  FOREIGN KEY (`sector_id`) REFERENCES `sectors`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (`person_id`) REFERENCES `persons`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Table structure for table `users`
--
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `profile` ENUM('Admin', 'Super-Admin') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--
LOCK TABLES `users` WRITE;
-- Placeholder for password_hash. This should be updated with a hash generated by PHP's password_hash().
-- The hash below is an EXAMPLE bcrypt hash. For actual deployment, generate a new hash for 'admin_password'
-- using src/utils/generate_password_hash.php and replace it here or update via application logic.
INSERT INTO `users` (`username`, `password_hash`, `profile`) VALUES
('admin', '\$2y\$10\$DHK9TkhqOrEiZfAl8mqEVeBHUoUt7xDSy.ocHCrYud6.kbYOjJeyK', 'Super-Admin');
UNLOCK TABLES;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS=1;

-- End of SQL Script
